// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-__lxXrca-qXspjQ7PesWPg4Whf-GuA',
    appId: '1:437534842036:web:13b64c22d1fd79f23d0be1',
    messagingSenderId: '437534842036',
    projectId: 'skladhelper-33701-da5a6',
    authDomain: 'skladhelper-33701-da5a6.firebaseapp.com',
    storageBucket: 'skladhelper-33701-da5a6.firebasestorage.app',
    measurementId: 'G-2GB1XNVJS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBafo3zY0dJPp5J6XCKa-Gm4o2d2muWIok',
    appId: '1:437534842036:android:810bfb7c86f318ae3d0be1',
    messagingSenderId: '437534842036',
    projectId: 'skladhelper-33701-da5a6',
    storageBucket: 'skladhelper-33701-da5a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9leU_jwNOXAYtf0t-ykQWFq54sc4Y04',
    appId: '1:437534842036:ios:195200ecd0f805773d0be1',
    messagingSenderId: '437534842036',
    projectId: 'skladhelper-33701-da5a6',
    storageBucket: 'skladhelper-33701-da5a6.firebasestorage.app',
    iosBundleId: 'kz.arystan.skladHelper33701',
  );
}
